### ISSUE TITLE
dragon dart

### ISSUE THREAD

**Issue by panzear** [pwatts6060/SuppliesTrackerExternal#32]
D darts are counted as mith darts

**Comment by Dyldozer** [comment]
Is this after changing dart type in config?

**Comment by Crystalknoct** [comment]
Mine show up as rune darts not sure why.

**Comment by pwatts6060** [comment]
Fixed in 3.0.0 so that whenever you check or add new darts to the bp, it updates the config with the current dart type. Mith darts is the default and the config had to be set manually which is why this issue was originally created.
