### ISSUE TITLE
What does the "switch tracking" button do?

### ISSUE THREAD

**Issue by davidponton** [pwatts6060/SuppliesTrackerExternal#48]
I'm trying to figure out what the "Switch Tracking" button does, and the wiki/readme doesn't really clarify that. Consider maybe adding an explanation for it. It's possible it's something really obvious and I'm just being dense, but still, doesn't hurt to explain everything in the readme.

**Comment by StevKast** [comment]
I looked through the code and I believe it's supposed to switch between the current session of supplies used and the all-time supplies used. I think it's currently broken though and there haven't been any updates to this plugin since Nov 2020 so I doubt it will be fixed.
