### ISSUE TITLE
Cannonballs being tracked as Headless Arrows

### ISSUE THREAD

**Issue by Owai-Seek** [pwatts6060/SuppliesTrackerExternal#52]
Did a Bloodveld Task in Meiyerditch Lab. When I checked my Supply Tracker, it had noted down ~2062 Headless Arrows had been used. (At a cost of 14.4k GP). The real price (if it had tracked cannonballs), would be ~324k.

![image](https://user-images.githubusercontent.com/7543955/155862056-3c3764ea-096a-4976-91a5-dc72eacfb280.png)

**Comment by pwatts6060** [comment]
Tested right now and issue still remains.

**Comment by pwatts6060** [comment]
Fixed in commit fb2147204bf55164b5b7be2a02e5f2a07358bf60 for version 3.0.0
Additionally fixed tracking for the ornamental cannon from shattered relic league.
