### ISSUE TITLE
Tracker stopped tracking supplies used from inventory after Jagex inventory update

### ISSUE THREAD

**Issue by Ryu2kGit** [pwatts6060/SuppliesTrackerExternal#56]
Most supplies used directly from the inventory are not tracked right now. That includes food, potions, teleport scrolls and tablets.

What still works:
- Runes used are still tracked, both from within the rune pouch and directly from the invent.
- Jewellery used still works
- Teleport scrolls, if used from master scroll book are also still tracked
-  as well as weapon charges. 
havent checked farming/prayer stuff

**Comment by pwatts6060** [comment]
What is the status of these things now? I stumbled on the teleport tabs being broken. Haven't tested anything else and I'm unaware of changes since this issue was reported

**Comment by pwatts6060** [comment]
Version 3.0.0 fixes most things hopefully. Following things I've fixed and tested:

- Bones burying
- bones on altar
- Food (cooked karambwan tested)
- Food with drink option (Jug of wine)
- Teleport scrolls
- Potions (various, was fixed before I think)
- Tablets (Ardougne tablet)
