### ISSUE TITLE
Tracker suddenly stopped tracking Potions and food.

### ISSUE THREAD

**Issue by shadowxrider420** [pwatts6060/SuppliesTrackerExternal#57]
I don't know if I just did some mistake in the Confug or so but the tracker suddenly stopped tracking Potions and food when i kill Vorkath. I used Combat pots pray pots etc. and anglerfish etc. Maybe someone knows this issue or know how to fix it. i tried reset and reinstall allready.
![image](https://user-images.githubusercontent.com/104165006/164531450-8003122f-67e1-488f-8281-48ffefee47e1.png)

**Comment by andrewjr** [comment]
I noticed this as well. Potions and food don't appear to be being tracked.

**Comment by starryskies2** [comment]
does anyone know if the creator is planning to fix it?for the past 1y or so he didnt change/update/fixed anything

**Comment by pwatts6060** [comment]
Fixed in commit 59a23cb798cd23129f50b63e00066080202ca520 in version 3.0.0
