### ISSUE TITLE
remember supplies after logging out

### ISSUE THREAD

**Issue by starryskies2** [pwatts6060/SuppliesTrackerExternal#72]
it was an option awhile back that allowed to track supplies used over months not just a single logging sess,is there a way to add it back?

**Comment by pwatts6060** [comment]
> it was an option awhile back that allowed to track supplies used over months not just a single logging sess,is there a way to add it back?

It should still be an option. Possibly I caused a bug with the update today. Check your config for the "current session by default" that should not be ticked. Also try clicking the switch tracking button which should toggle between all time history and current session.

**Comment by starryskies2** [comment]
Thats the problem,its been like that waay before the update,idk if its
something i caused or general thing,none of those options works

בתאריך יום ה׳, 15 בספט׳ 2022, 18:24, מאת Patrick Watts ‏<
***@***.***>:

**Comment by Zelden848** [comment]
Could be linked to this - https://github.com/pwatts6060/SuppliesTrackerExternal/issues/78

**Comment by starryskies2** [comment]
yeah it is,im using the  offical launcher
