### ISSUE TITLE
masori assembler

### ISSUE THREAD

**Issue by menogs** [pwatts6060/SuppliesTrackerExternal#73]
hello my dear friends, the masori assembler isnt working as intended, as it assumes every dart i use on blowpipe is without any kind of assembler, so every time it counts as 1 used.

as idk how to code myself, i'm here to report the issue. Thx for the plugin, so useful tracking my supplies :)

sorry for my bad english, this isnt my natural language :(

**Comment by pwatts6060** [comment]
Thanks for reporting, will try get it fixed soon

**Comment by menogs** [comment]
thank you for your efforts!

**Comment by pwatts6060** [comment]
Added in `7109cc6862e60c44cb6556cc932794aee6336dff` sorry for delays. It also needs to get approval now.
