### ISSUE TITLE
All time session not saved when using the Jagex launcher for Runelite

### ISSUE THREAD

**Issue by Osmoldd** [pwatts6060/SuppliesTrackerExternal#78]
![image](https://user-images.githubusercontent.com/112002993/213429130-2a272b3d-7c3b-4e6f-a97f-a48ac6394848.png)
When using the Jagex launcher to use Runelite, the Supplies Tracker does not keep track of the all time session, it constantly reset when restarting the client despite having the option properly selected.

Tested by launching RL alone and it seems to work, but as I use the Jagex's client for ease of use and switching with accounts, this proves to be a bit inconvenient. Other plugins trackers seems to work fine

**Comment by Zelden848** [comment]
Bumping this, would be great to see a fix given the introduction of Jagex Accounts

**Comment by pwatts6060** [comment]
This has been fixed though I have reverted the current session by default option as it seemed buggy.
