### ISSUE TITLE
Teleport spheres in food category

### ISSUE THREAD

**Issue by Ardnij123** [pwatts6060/SuppliesTrackerExternal#88]
When using [teleport spheres](https://oldschool.runescape.wiki/w/Teleport_sphere) they are shown in food category in the tracker. They should be shown in teleports.

Bug is at least in Plain of mud sphere, others I have not tried.
![image](https://github.com/pwatts6060/SuppliesTrackerExternal/assets/75635094/56e78de5-ff3a-4331-9be9-54536313093e)

**Comment by pwatts6060** [comment]
Thanks, should be fixed in next update
