### ISSUE TITLE
Barrows prayer potions and strange lockpick

### ISSUE THREAD

**Issue by EduAndrade93** [pwatts6060/SuppliesTrackerExternal#89]
I'm doing Barrows and the plugin is not tracking the consumption of Prayer potions, Strange old lockpick loads or teleports home
![image](https://github.com/pwatts6060/SuppliesTrackerExternal/assets/163664654/462af3ec-280d-4829-a40b-a5cbd576b905)

**Comment by EduAndrade93** [comment]
To be more specific, I'm making barrows, using magic and prayer potions during the dungeon and eventually some food
I noticed that while doing Barrows the plugin does not record the use of magic potions, prayer potions, food (Manta ray), the cost of Strange old lockpick and the use of house teleport tabs

**Comment by dean14367** [comment]
When embarking on the Barrows mini-game in Old School RuneScape, adventurers often rely on prayer potions and the strange old lockpick to enhance their chances of success. Prayer potions [barrow or borrow](https://differencewise.com/barrow-vs-borrow/) are essential as they replenish prayer points, which are crucial for maintaining protective prayers against the formidable Barrows Brothers.

**Comment by pwatts6060** [comment]
I drank prayer pots inside a barrows room and inside the tunnel and they both were tracked
Closing this issue unless someone else can reproduce
