### ISSUE TITLE
Ornament Kits on Blowpipe show the same charges as a regular Toxic Blowpipe

### ISSUE THREAD

**Issue by edafs** [pwatts6060/SuppliesTrackerExternal#90]
The regular blowpipe (https://oldschool.runescape.wiki/w/Toxic_blowpipe#Charged) and the ornamented version of it (https://oldschool.runescape.wiki/w/Blazing_blowpipe#Charged) show the same charges with this plugin.

**Comment by pwatts6060** [comment]
If they are tracked with the same symbol and charges that doesn't seem to be a problem unless I'm misunderstanding. A cosmetic kit should be unrelated to the charge tracking.
